import { v4 as uuid } from "uuid";

export const DashboardMenu = [
  // {
  // 	id: uuid(),
  // 	title: 'Authentication',
  // 	icon: 'lock',
  // 	children: [
  // 		{ id: uuid(), link: '/authentication/sign-in', name: 'Sign In' },
  // 		{ id: uuid(), link: '/authentication/sign-up', name: 'Sign Up' },
  // 		{ id: uuid(), link: '/authentication/forget-password', name: 'Forget Password'}
  // 	]
  // },
  {
    id: uuid(),
    title: "Dashboard",
    icon: "home",
    link: "/",
  },
  {
    id: uuid(),
    title: "Academic",
    icon: "book",
    children: [
      {
        id: uuid(),
        link: "#",
        title: "Master",
        icon:'folder',
        children: [
          {
            id: uuid(),
            link: "#",
            title: "Academic Master",
            icon: "book-open",
            children: [
              {
                id: uuid(),
                link: "/pages/academic/master/commonmaster/bankdetails",
                name: "Bank Details",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/master/academicdata/academicyear",
                name: "Academic Year",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/master/academicdata/feecategory",
                name: "Fee Category",
                icon: "file-text",
              },
              // {
              //   id: uuid(),
              //   link: "/pages/academic/master/academicdata/studenttype",
              //   name: "Student Type",
              // },
              {
                id: uuid(),
                link: "/pages/academic/master/academicdata/concession",
                name: "Concession",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/master/academicdata/medium",
                name: "Medium",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/master/academicdata/division",
                name: "Division",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/master/academicdata/certificate",
                name: "Certificate",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/master/academicdata/occupation",
                name: "Occupation",
                icon: "file-text",
              },
            ],
          },
          {
            id: uuid(),
            link: "#",
            title: "Common Master",
            icon: "book-open",
            children: [
              {
                id: uuid(),
                link: "/pages/academic/master/commonmaster/castedetails",
                name: "Caste Details",
                icon: "file-text",
              },
              // { id: uuid(), link: '/pages/academic/master/commonmaster/castecategory', name: 'Caste Category' },
              // { id: uuid(), link: '/pages/academic/master/commonmaster/subcaste', name: 'Sub Caste' },
              {
                id: uuid(),
                link: "/pages/academic/master/commonmaster/title",
                name: "Title",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/master/commonmaster/gender",
                name: "Gender",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/master/commonmaster/religion",
                name: "Religion",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/master/commonmaster/maritalstatus",
                name: "Marital Status",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/master/commonmaster/handicap",
                name: "Handicap",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/master/commonmaster/bloodgroup",
                name: "Blood Group",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/master/commonmaster/universityandboard",
                name: "University And Board",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/master/commonmaster/nationality",
                name: "Nationality",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/master/commonmaster/mothertongue",
                name: "Mother Tongue",
                icon: "file-text",
              },
            ],
          },
        ],
      },
      {
        id: uuid(),
        link: "#",
        title: "Pre Admission",
        icon:'folder',
        children: [
          {
            id: uuid(),
            link: "#",
            title: "Course Configuration",
            icon: "book-open",
            children: [
              {
                id: uuid(),
                link: "/pages/academic/preadmission/course/year",
                name: "Year",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/course/semester",
                name: "Semester",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/course/degree",
                name: "Degree",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/course/faculty",
                name: "Faculty",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/course/feepattern",
                name: "Fee Pattern",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/course/coursepattern",
                name: "Course Pattern",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/course/receiptbook",
                name: "Receipt Book",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/course/feehead",
                name: "Fee Head",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/course/feeheadgrouping",
                name: "Fee Head Grouping",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/course/feeheadaccountmapping",
                name: "Fee Head Account Mapping",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/course/cashbookrights",
                name: "Cashbook Rights",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/course/copycashbookrights",
                name: "Copy Cashbook Rights",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/course/coursecertificate",
                name: "Course Certificate",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/course/useraccess",
                name: "User Access",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/course/prnnumberconfig",
                name: "PRN Number Config",
                icon: "file-text",
              },
            ],
          },
          {
            id: uuid(),
            link: "#",
            title: "Fees Configuration",
            icon: "book-open",
            children: [
              {
                id: uuid(),
                link: "/pages/academic/preadmission/fees/basiccourse",
                name: "Programme",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/fees/coursecreation",
                name: "Course Creation",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/fees/courseupdation",
                name: "Course Updation",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/fees/coursesection",
                name: "Course Division",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/fees/feestructure",
                name: "Fee Structure",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/fees/copystandardfee",
                name: "Copy Standard Fee",
                icon: "file-text",
              },
            ],
          },
          {
            id: uuid(),
            link: "#",
            title: "Other Fees Definition",
            icon: "book-open",
            children: [
              {
                id: uuid(),
                link: "/pages/academic/preadmission/otherfeesdefination/generalfine",
                name: "General Fine",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/otherfeesdefination/courseinstallment",
                name: "Course Installment",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/otherfeesdefination/studentinstallment",
                name: "Student Installment",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/otherfeesdefination/certificatefee",
                name: "Certificate Fee",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/preadmission/otherfeesdefination/erasestudentinstallment",
                name: "Erase Student Installment",
                icon: "file-text",
              },
            ],
          },
        ],
      },
      {
        id: uuid(),
        link: "#",
        title: "Transaction",
        icon:'folder',
        children: [
          {
            id: uuid(),
            link: "#",
            title: "Admission Fees",
            icon: "book-open",
            children: [
              {
                id: uuid(),
                link: "/pages/academic/transaction/admissionfees/studentadmission",
                name: "Student Admission",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/admissionfees/feescollection",
                name: "Fees Collection",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/admissionfees/receiptreconciliation",
                name: "Receipt Reconciliation",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/admissionfees/outstandingfees",
                name: "Outstanding Fees",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/admissionfees/feesconcession",
                name: "Fees Concession",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/admissionfees/feesrefund",
                name: "Fees Refund",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/admissionfees/receivedscholarshipentry",
                name: "Received Scholarship Entry",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/admissionfees/changefeesstudent",
                name: "Change Fees- Student",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/admissionfees/createotherfeesbulk",
                name: "Create Other Fees - Bulk",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/admissionfees/changefeesbulk",
                name: "Change Fees - Bulk",
                icon: "file-text",
              }, //Student Type
              {
                id: uuid(),
                link: "/pages/academic/transaction/admissionfees/createfeesregisteredpromoted",
                name: "Create Fees - Registered/Promoted",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/admissionfees/studentdirectadmissionye",
                name: "Student Direct Admission YE",
                icon: "file-text",
              },
            ],
          },
          {
            id: uuid(),
            link: "#",
            title: "Other Fees",
            icon: "book-open",
            children: [
              {
                id: uuid(),
                link: "/pages/academic/transaction/otherfees/collectotherfees",
                name: "Collect Other Fees",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/otherfees/generalfinecollection",
                name: "General Fine Collection",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/otherfees/changeotherfeesstudent",
                name: "Change Other Fees -Student",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/otherfees/changeotherfeesbulk",
                name: "Cancel Other Fees - Bulk",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/otherfees/feeheadwisechangeotherfeesbulk",
                name: "Fee Head Wise Change Other Fees - Bulk",
                icon: "file-text",
              },
            ],
          },
          {
            id: uuid(),
            link: "#",
            title: "Receipts",
            icon: "book-open",
            children: [
              {
                id: uuid(),
                link: "/pages/academic/transaction/receipts/canceladmission",
                name: "Cancel Admission",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/receipts/cancelpromotion",
                name: "Cancel Promotion",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/receipts/receiptcancellationandreprint",
                name: "Receipt Cancel and Reprint",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/receipts/adminreceiptcancellationandreprint",
                name: "Admin Receipt Cancellation And Reprint",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/receipts/coursechange",
                name: "Course Change",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/receipts/feetypechange",
                name: "Change Fee Category",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/receipts/onlinepaymentrequery",
                name: "Online Payment Requery",
                icon: "file-text",
              },
            ],
          },
          {
            id: uuid(),
            link: "#",
            title: "Administrative Work",
            icon: "book-open",
            children: [
              {
                id: uuid(),
                link: "/pages/academic/transaction/administrativework/studentinformation",
                name: "Student Details",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/administrativework/studentsubjectupdation",
                name: "Student Subject",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/administrativework/rollnoupdation",
                name: "Roll No Allotment",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/administrativework/bulkupdation",
                name: "Student Data Update -Bulk",
                icon: "file-text",
              },
              
              {
                id: uuid(),
                link: "/pages/academic/transaction/administrativework/outstandingfeesremainder",
                name: "Outstanding Fees Remiander",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/administrativework/scholarshipdataentry",
                name: "Sanctioned Scholarship Entry",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/administrativework/bulkemail",
                name: "Send Email - Bulk",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/administrativework/scholarshipdetailsentry",
                name: "Scholarship Application Entry",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/administrativework/railwayconcessionapproval",
                name: "Railway Concession Approval",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/administrativework/studentdocumentdetails",
                name: "Student Document Details",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/administrativework/studentdocumentreceipt",
                name: "Student Document Receipt",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/administrativework/prnallotment",
                name: "PRN Allotment",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/transaction/administrativework/subjectgroupwisesection",
                name: "Subject Groupwise Section",
                icon: "file-text",
              },
              // { id: uuid(), link: '/pages/academic/transaction/administrativework/sectionallocation', name: 'Section Allocation(YE/PROADM)' },
              // { id: uuid(), link: '', name: 'Subject Groupwise Roll No' },
            ],
          },
        ],
      },
      {
        id: uuid(),
        link: "#",
        title: "Fees Reports",
        icon:'folder',
        children: [
          {
            id: uuid(),
            link: "#",
            title: "Fees Report",
            icon: "book-open",
            children: [
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/dcrreport",
                name: "DCR Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/demandreport",
                name: "Demand Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/studentledger",
                name: "Student Ledger",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/bankreport",
                name: "Bank Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/receiptcancellationreport",
                name: "Receipt Cancellation Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/userwisecollectionreport",
                name: "Userwise Collection Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/outstandingfeesreport",
                name: "Outstanding Fees Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/admissioncancellationreport",
                name: "Admission Cancellation Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/feesrefundreport",
                name: "Fees Refund Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/feesconcessionreport",
                name: "Fees Concession Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/feesreceivablereport",
                name: "Fees Receivable Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/adjustedreceiptreport",
                name: "Adjusted Receipt Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/outstandingsummaryreport",
                name: "Outstanding Summary Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/coursewisedcrreport",
                name: "Course Wise DCR Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/challanreconciliationreport",
                name: "Challan Reconciliation Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/installmentoutstandingreport",
                name: "Installment Outstanding Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/feesreconciliationreport",
                name: "Fees Reconciliation Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/duereport",
                name: "Due Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/feesreport/receiptreprintbulk",
                name: "Receipt Reprint-Bulk",
                icon: "file-text",
              },
            ],
          },
          {
            id: uuid(),
            link: "#",
            title: "Online Payment Report",
            icon: "book-open",
            children: [
              {
                id: uuid(),
                link: "/pages/academic/feesreports/onlinepaymentreport/paymentgatewaytransactionsreport",
                name: "Payment Gateway Transactions Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/onlinepaymentreport/settlementdcrreport",
                name: "Settlement DCR Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/onlinepaymentreport/settlementdatewisedcr",
                name: "Settlement DateWise DCR",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/onlinepaymentreport/cashbookwisesettlementdcr",
                name: "CashbookWise Settlement DCR",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/feesreports/onlinepaymentreport/settledunsettledreceipt",
                name: "Settled Unsettled Receipt",
                icon: "file-text",
              },
            ],
          },
        ],
      },
      {
        id: uuid(),
        link: "#",
        title: "Student Reports",
        icon:'folder',
        children: [
          {
            id: uuid(),
            link: "#",
            title: "Admission",
            icon: "book-open",
            children: [
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/promotedapplicationreport",
                name: "Promoted Application Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/customizedstudentreportexcel",
                name: "Customized Student Report - Excel",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/provisionaladmissionreport",
                name: "Provisional Admission Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/admissionreport",
                name: "Admission Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/coursewisestrengthreport",
                name: "Coursewise Strength Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/admissionpositionreport",
                name: "Admission Position Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/studentcompletedetailsexcel",
                name: "Student Complete Details - Excel",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/courseandcategorychange",
                name: "Course & Fee Category Change",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/blankattendancesheet",
                name: "Blank Attendance Sheet",
                icon: "file-text",
              },
              //extra//{ id: uuid(), link: '/pages/academic/studentreport/admission/coursewisestudentadmissionreport', name: 'Coursewise Student Admission Report' },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/rollcallreport",
                name: "Roll Call Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/smssendreport",
                name: "SMS Send Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/lateraladmissionreport",
                name: "Lateral admission Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/photosignreport",
                name: "Photo Sign Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/studentapplycertificatereport",
                name: "Student Apply Certificate Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/studentadmissioncancellationrequestreport",
                name: "Student Admission Cancellation Request Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/admission/studenteligibilityreport",
                name: "Student Eligibility Report",
                icon: "file-text",
              },
            ],
          },
          {
            id: uuid(),
            link: "#",
            title: "MIS",
            icon: "book-open",
            children: [
              {
                id: uuid(),
                link: "/pages/academic/studentreport/MIS/studentmis",
                name: "Student MIS Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/MIS/cashbookwisemisreport",
                name: "Cash BookWise MIS Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/MIS/studentmiscastewise",
                name: "Student MIS Caste Wise",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/MIS/subjectwisereport",
                name: "Subject Wise Report",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/academic/studentreport/MIS/subjectdivisionreport",
                name: "Subject & Division Report",
                icon: "file-text",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: uuid(),
    link: "#",
    title: "NEP",
    icon: "home",
    children: [
      {
        id: uuid(),
        link: "#",
        title: "Master",
        icon:'folder',
        children: [
          {
            id: uuid(),
            link: "#",
            title: "Masters",
            icon: "book-open",
            children: [
              {
                id: uuid(),
                link: "/pages/nep/master/masters/boardofstudy",
                name: "Board Of Study",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/nep/master/masters/subjectcategory",
                name: "Subject Category",
                icon: "file-text",
              },
              {
                id: uuid(),
                link: "/pages/nep/master/masters/discipline",
                name: "Discipline",
                icon: "file-text",
              },
            ],
          },
        ],
      },
    ],
  },
];

export default DashboardMenu;
